// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioMVC.Data;

#nullable disable

namespace PortfolioMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PortfolioMVC.Models.ContactMessage", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<bool>("IsRead").HasColumnType("tinyint(1)");
                b.Property<string>("Message").IsRequired().HasColumnType("longtext");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<DateTime>("SentAt").HasColumnType("datetime(6)");
                b.Property<string>("Subject").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)");
                b.HasKey("Id");
                b.ToTable("ContactMessages");
            });

            modelBuilder.Entity("PortfolioMVC.Models.Project", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("Description").IsRequired().HasColumnType("longtext");
                b.Property<string>("GitHubUrl").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("ImageUrl").HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<bool>("IsFeatured").HasColumnType("tinyint(1)");
                b.Property<string>("LiveUrl").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("TechStack").HasMaxLength(300).HasColumnType("varchar(300)");
                b.Property<string>("Title").IsRequired().HasMaxLength(150).HasColumnType("varchar(150)");
                b.HasKey("Id");
                b.ToTable("Projects");
            });

            modelBuilder.Entity("PortfolioMVC.Models.Skill", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Category").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int>("Proficiency").HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("Skills");
            });
#pragma warning restore 612, 618
        }
    }
}
